"use client";
import "./globals.css";
import { Inter } from "next/font/google";

import LeftBar from "@/components/leftbar/Leftbar";
import Rightbar from "@/components/rightbar/Rightbar";
import Searchbar from "@/components/searchbar/Searchbar";
import { ThemeProvider } from "next-themes"
import type { AppProps } from 'next/app'

// ******* Wallet Kitt**** 

import "@rainbow-me/rainbowkit/styles.css";
import {
  getDefaultWallets,
  RainbowKitProvider,
  lightTheme,
} from "@rainbow-me/rainbowkit";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { mainnet, polygon, optimism, arbitrum, zora } from "wagmi/chains";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";
import BottomBar from "@/components/bottomBar/BottomBar";

const { chains, publicClient } = configureChains(
  [mainnet, polygon, optimism, arbitrum, zora],
  [alchemyProvider({ apiKey: "process.env.ALCHEMY_ID" }), publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  projectId: "YOUR_PROJECT_ID",
  chains,
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
});

// ***** Wallet Kit *****
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
  etc,
}: {
  children: React.ReactNode;
  etc: any;
  
}) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
      <ThemeProvider attribute="class">
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider
            chains={chains}
            coolMode  
            theme={lightTheme({
              accentColor: "#7b3fe4",
              accentColorForeground: "white",
              borderRadius: "medium",
              fontStack: "system",
              overlayBlur: "small",
            })}
            {...etc}
          >
           <main>
            <div className="flex fixed dark:bg-[#121212] bg-[#F9F6FE]  md:h-full w-full">
              <LeftBar /> 
              <div className="flex h-full w-[100vw] md:w-[82vw]  flex-col">
                <Searchbar />

                <div className="flex flex-col md:flex-row md:pb-6 h-v[100vh] md:h-[88vh] w-full bg-blue-600">
                  <div className="main-children md:pl-6 px-5 flex flex-col items-end h-[70vh]  md:min-h-[77vh] md:min-w-[57vw] w-full">
                    {children}

                  </div>
                  <BottomBar/>
                  
                  <Rightbar />
                </div>
              </div>
            </div>
            </main>
          </RainbowKitProvider> 
        </WagmiConfig>
        </ThemeProvider>
         
           
      </body>
    </html>
  );
}
